name: Update README

on:
  push:
    branches: [main]
  schedule:
    - cron: "30 6 * * */1"

permissions:
  contents: write

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: go run github.com/muesli/markscribe@d838b6e71dc673e8a3ef248b0e75fbd44ce8cc4c -write README.md templates/README.md.tpl
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - uses: oven-sh/setup-bun@v2
      - run: bunx markdown-to-html-cli *.md **/*.md --output "."

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated README
          branch: main
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>
